### ISSUE TITLE
Expected a value of type 'AbstractControl<String>', but got one of type 'FormControl<dynamic>'

### ISSUE THREAD

**Issue by gibahjoe** [joanpablo/reactive_forms#100]
Hi,

After upgrading to 9.0.1, I get the following error in the title `Expected a value of type 'AbstractControl<String>', but got one of type 'FormControl<dynamic>'`.  I am not sure why this is a problem since form control does inherit abstract control.

**Comment by joanpablo** [comment]
Hi @gibahjoe,

Thanks for using Reactive Forms. COuld you please show me how you are defining the FormGroup and how you are binding controls with widgets?

Basically in version 9.x.x I have made a little more strict the type definition to minimize the runtime errors (or at least throw an error more explicitly when there is a cast error).  

But basically, the error is saying that one of your widgets is expecting a control of type **String** and you are providing a Control of type **dynamic** (and because dynamic is not a subtype of String then the error is thrown).

If you show me your code I can help you address the issue.

Best regards

**Comment by gibahjoe** [comment]
Thanks.

Your explanation really helped me figure out where the issue was. I had to specify the type `<String>` on all my controls on the page in question. Thanks again.
