### ISSUE TITLE
New library flutter_forms difference

### ISSUE THREAD

**Issue by sokolej79** [joanpablo/reactive_forms#114]
New library for flutter forms similar to reactive_forms has been published.
Both are like angular reactive_forms for flutter.
What is the difference between these two libraries?
Pros/cons?

**Comment by sokolej79** [comment]
Link to new library:
https://pub.dev/packages/flutter_forms

**Comment by kuhnroyal** [comment]
That is a blatant steal...

**Comment by vasilich6107** [comment]
@sokolej79 main cons of `flutter_forms`

- less features
- less components
- bloated with dependencies while `reactive_forms` depends only on `flutter` and `intl`

**Comment by joanpablo** [comment]
Hi @sokolej79,

Thanks for the issue, if it wasn't for your issue I probably wouldn't know that a new library with almost the same names was released. Each time I have decided to contribute to the community I first make deep research on the Internet to see if somebody else already has implemented the solution I'm looking for. And only after deep research and a lot of time testing different solutions from other developers, if I don't find a solution that I can reutilize and that feet my needs, only then, I create my solution, and share it with the community only if I think it can be useful to somebody else.

That's is how Reactive Forms born. Only after I have tested many and many (if not all) of the Flutter plugins related to forms in www.pub.dev. I even tried to use the official Reactive Forms from Angular Dart. But none of those solutions feet my needs, many were too complex or incomplete. 

I decided then to create my own library in a project I was working on at that time, a project full of Forms. After I have created the first version of my personal (The first version of Reactive Forms), I realized that I was able to reuse it in my second Flutter project because it was written very generically (I make very emphasis on making it very reusable). At that time I decided that it could be a great opportunity to share my implementation as a plugin and create officially Reactive Forms. 

While I was implementing all the features that I needed and used in real projects, I carefully studied the JavaScript and Dart implementation of Angular. I realize that the Dart version was very poor and lack of many features that I needed (don't misunderstand me Angular Dart implementation is a great library), and also it was too tight to the web environment (of course the implementation was focus on Angular Dart, not Flutter), I needed something related to Flutter environment.

I released the official Reactive Forms in Flutter, and start publishing some posts in www.dev.to: [Why use Reactive Forms in Flutter?](https://dev.to/joanpablo/why-use-reactive-forms-in-flutter-ea1), [Star Rating with Flutter Reactive Forms](https://dev.to/joanpablo/star-rating-with-flutter-reactive-forms-2d52) and Medium. 

I suppose that the intentions of the creator of the library [flutter_forms](https://pub.dev/packages/flutter_forms) aren't bad,  maybe he just forgets to make a deep research before publishing his version, and could have saved a lot of effort and time from his site. Unfortunately, now there are going to be many new developers confused, about the two libraries that have almost the same name and even almost the same classes and data type names.

Right now Reactive Forms have a great community, I need to release a new version this week. I hope that the community continues supporting Reactive Forms with new issues and pull requests.
