### ISSUE TITLE
ReactiveSlider integer

### ISSUE THREAD

**Issue by DevNico** [joanpablo/reactive_forms#138]
I have an integer value that can either get edited in a `ReactiveTextField` or with a `ReactiveSlider`. The problem ist `ReactiveSlider` only accepts a `FormControl<double>`.

I'd like to create a `ReactiveSlider` with a `FormControl<int>`.

**Comment by joanpablo** [comment]
Hi @DevNico,

ReactiveSlider is using double because the Flutter Slider uses double by default. 

Maybe we can add a **control value accessor** for ReactiveSlider for converting from int to double. I didn't include a value accessor for Slider, but I think is a good idea to add one. In the end, almost all other Reactive widgets have the control value accessor.

I will implement it and I will let you know

Thanks Best regards

**Comment by joanpablo** [comment]
Hi @DevNico,

I have just released a new version of Reactive Forms, version 10.3.0. In this version, you can Bind a FOrmControl of type **int** to a ReactiveSlider.

Don't hesitate to reopen the issue or create a new one if something is missing.

Best regards.
