### ISSUE TITLE
What is the difference between ReactiveForm and ReactiveFormBuilder?

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#206]
Hi @joanpablo 

According to the documentation in files they do the same thing

```dart
/// This class is responsible for create a [FormControlInheritedStreamer] for
/// exposing a [FormGroup] to all descendants widgets.
///
/// It also configures the inner [FormControlInheritedStreamer] to rebuild
/// context each time the [FormGroup.status] changes.
class ReactiveFormBuilder extends StatefulWidget {
```

```dart
/// This class is responsible for create a [FormControlInheritedStreamer] for
/// exposing a [FormGroup] to all descendants widgets.
///
/// It also configures the inner [FormControlInheritedStreamer] to rebuild
/// context each time the [FormGroup.status] changes.
class ReactiveForm extends StatefulWidget {
```

**Comment by joanpablo** [comment]
Hi @vasilich6107 

basically, the main difference is that one acts like a Builder (with a builder function) and is a Stateful widget, the other one is a stateless widget. If you use a Controller or Model/Bloc you can use the Stateless widget (ReactiveForm), otherwise, if you want to declare the form in the same widget you may use the ReactiveFormBuilder, anyway, there is no real formula you can use any of them in any situation.
