### ISSUE TITLE
[BUG] Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by naamapps** [joanpablo/reactive_forms#266]
Hey,
Getting this error message from time to time..

Not sure how to replicate,
but the solution is to check if the `_focusChanges` stream is closed before adding to it.
```
I/flutter (11773): Bad state: Cannot add new events after calling close
I/flutter (11773): #1      FormControl._updateFocusState (package:reactive_forms/src/models/models.dart:948)
I/flutter (11773): #2      FormControl._onFocusControllerChanged (package:reactive_forms/src/models/models.dart:936)
```

**Comment by joanpablo** [comment]
Hi @naamapps,

Are you are calling the __dispose()__ method on a FormControl or FormGroup or FormArray?

**Comment by joanpablo** [comment]
Hi @naamapps,

You don't necessarily need to provide a FocusNode to a ReactiveFormField, in that case, ReactiveFormField will dispose of the FocusNode (the [FocusController](https://github.com/joanpablo/reactive_forms/blob/ea8148de4e92a0554ee42aacdc182689b5a1e887/lib/src/models/focus_controller.dart#L68) will do it). But if you provide a custom FocusNode, then you will need to dispose it manually.

**Comment by naamapps** [comment]
The docs doesn't mention we need to call it, but I know there are streams and other things that needs to be disposed in order to prevent memory leaks.
I'm just confused as to what is the meaning of the dispose functions if no one ever calls them.

**Comment by joanpablo** [comment]
Hi @naamapps,

If you don't provide the FocusNode, the Reactive Form package will dispose all the FocusNodes when the widgets get destroyed. If you provide the FocusNode it means that you need to take care of it by your own. You need to find the moment in which the Widgets get destroyed and dispose manually the FocusNode.

If you get an error maybe is because you are disposing the FocusNode before the Widget gets destroyed, and then are trying to indirectly use the FocusNode, not sure your error because you are not given further details.

**Comment by naamapps** [comment]
Yes I got that part @joanpablo - I wrote that I do dispose the FocusNodes manually.

> Well I am disposing the focus nodes manually

My questions above are not connected to the error I wrote in the main issue - I'm just concerned about memory leaks.

> Is it necessary to call it (the dispose function) at all? (regardless of the focusNode).

> I'm just confused as to what is the meaning of the dispose functions if no one ever calls them.

Hope this is clearer,
Thanks

**Comment by joanpablo** [comment]
Hi @naamapps,

Sorry the late answare. I guess that you already have solve the issue because we have not hear any update from you.

Regarding the **dispose** method on AbstractControl, it is up to you to decide when to call it. The method basically clear all subscriptions:

```dart
/// Disposes the control
  void dispose() {
    _statusChanges.close();
    _valueChanges.close();
    _asyncValidationSubscription?.cancel();
  }
```

All Reactive widgets unsubscribe from Controls when they are disposed of. So no need to directly call the dispose method on a FormGroup or Control, but it always depends on the developer code.
