### ISSUE TITLE
Proposal / validationMessages on FormControl

### ISSUE THREAD

**Issue by mcrio** [joanpablo/reactive_forms#325]
Hi, thanks for the awesome library.

I didn't find an earlier discussion but maybe we could add an option to specify `validationMessages` when instantiating `FormControl`. Saying as currently validators are defined on `FormControl` level while the messages are defined on the input widget level, so it feels kinda disconnected and not in one place.

The current functionality could be kept saying if `validationMessages` exists on widget level, combine them with the ones defined on FormControl.

**Comment by joanpablo** [comment]
Hi @mcrio,

Thanks for your kind words, and for using Reactive Forms.

The validation Messages are placed in Widgets because it is intended to use it with i18n (internationalization), and most of the i18n libraries use the `BuildContext` to access i18n messages. On the other hand, FormGroup and FormControl are intended to be declared in Bloc/Controller/ModelView, and is the holder of data and validators of the data.

But if you have an example or any use case feel free to post it here and share it with us. I will be more than glad to give it a look.

**Comment by mcrio** [comment]
Thanks @joanpablo 

Ok, I see what you are saying.

Some libraries provide static getters but I guess that way widgets won't be rebuilt when the locale is updated. The question is if the rebuild of the field error message is needed.

Considering what you wrote I'll close the issue/proposal, as it seems that introducing an additional `validationMessages` to FormControl would introduce complexity and might be confusing.
