### ISSUE TITLE
ReactiveTextField should support `autofillHints`

### ISSUE THREAD

**Issue by CDDelta** [joanpablo/reactive_forms#41]
ReactiveTextField should support `autofillHints` as shown [here](https://medium.com/flutter-community/level-up-your-flutter-apps-with-autofill-1418a02db2e0) and in the constructor docs [here](https://api.flutter.dev/flutter/material/TextFormField-class.html).

This is an awesome package btw! 🥇

**Comment by joanpablo** [comment]
Hi @CDDelta,

Thanks for the issue. I think you're right about include autofills. That's a feature that some other people asked me to include. The main reason I haven't do it yet is because, as far as I understand, It is only available from Flutter 1.20. That will break the compatibility with Flutter 1.17 clients. 

I'm planning to release a new version soon. In that version I'll not include autofill, but after that I will think how to maintain two versions of Reactive Forms, one for Flutter 1.17 and another Flutter 1.20 that includes autofill.

Thanks again.

**Comment by ayushin** [comment]
How is autofillHints would be a breaking change? It's just an extra argument to pass and if the parent widget does not have or use it - there should be no problem.

**Comment by kuhnroyal** [comment]
> How is autofillHints would be a breaking change? It's just an extra argument to pass and if the parent widget does not have or use it - there should be no problem.

But then how do you know when to pass it to the parent widget? The parameter does not exist in 1.17.

**Comment by ayushin** [comment]
I guess you could make a compatibility widget inheriting TextField with the autofillHints override in it's constructor.

But with flutter stable now at 2.0.3 is this longer relevant?

**Comment by joanpablo** [comment]
Hi @ayushin,

This is the older issue. At the moment of the issue, the version of the library was in Flutter 1.17. After I Have released the Flutter 2.0 version, then I will work on this issue.

Best regards.

**Comment by joanpablo** [comment]
Hi @CDDelta,

I have released a version supporting autofillHints, please check it and reopen the issue if you find some troubles or open a new one.

Thanks for your patient, this is actually the older issue in repo :)

**Comment by CDDelta** [comment]
Wonderful. Thank you for your great work @joanpablo!
