### ISSUE TITLE
How i can implement input with curreny format ?

### ISSUE THREAD

**Issue by danbn-100295** [joanpablo/reactive_forms#43]
How i can implement input with curreny format ?

**Comment by danbn-100295** [comment]
I want apply this package ?
https://pub.dev/packages/flutter_masked_text
How i can implement it ?

**Comment by joanpablo** [comment]
Hi @danbn-100295,

Thanks for the issue and for using **Reactive Forms**.

You need a [TextInputFormatter](https://api.flutter.dev/flutter/services/TextInputFormatter-class.html) for that task. 

You can implement a custom **TextInputFormatter** that fits your needs or use some flutter plugin.

There are several plugin based in TextInputFormatter, here are some of them:
- [mask_text_input_formatter](https://pub.dev/packages/mask_text_input_formatter).
- [text_input_mask_formatter](https://pub.dev/packages/text_input_mask_formatter).
- [currency_text_input_formatter](https://pub.dev/packages/currency_text_input_formatter).

Then you simply add the input formatter to the **ReactiveTextField**:

```dart
ReactiveTextField(
   formControlName: 'amount',
   formatters: [
      MaskTextInputFormatter(
         mask: '#.##', 
         filter: { "#": RegExp(r'[0-9]') },
      ),
   ],
),
```

**Comment by marcos930807** [comment]
Hi @danbn-100295 
If you necessarily need to use that package, since for the currency mask it brings many options (it is the one I use) that is how I achieve it.
Before knowing reactive_form, I already had a widget that passed the information of the currency, and when I wanted to obtain the current value, what I did was obtain it via controller.numberValue this is a simplified Version.

class CurrencyTextField extends StatefulWidget {
  CurrencyTextField({
    Key key,
    this.onChangeAmount,
    this.errorText,
  }) : super(key: key);

  final ValueChanged<double> onChangeAmount;
  final String errorText;

  @override
  _CurrencyTextFieldState createState() => _CurrencyTextFieldState();
}

class _CurrencyTextFieldState extends State<CurrencyTextField> {
  MoneyMaskedTextController controller;
  @override
  void initState() {
    super.initState();
    controller =
        MoneyMaskedTextController(); // Customize with your own currency Info
  }

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: controller,
      keyboardType: TextInputType.number,
      decoration: InputDecoration(
        errorText: widget.errorText,
      ),
      inputFormatters: [],
      onChanged: (value) => widget.onChangeAmount?.call(controller.numberValue),
    );
  }
}

Then i Created my own ReactiveWidget like the example in the Wiki:

class ReactiveMoneyMakedText extends ReactiveFormField<double> {
  ReactiveMoneyMakedText({
    @required String formControlName,
    final Map<String, String> validationMessages,
  }) : super(
            formControlName: formControlName,
            showErrors: (control) {
              return control.invalid;
            },
            validationMessages: validationMessages,
            builder: (ReactiveFormFieldState<double> field) {
              return CurrencyTextField(
                errorText: field.errorText,
                onChangeAmount: (value) => field.didChange(value),
              );
            });

  @override
  ReactiveFormFieldState<double> createState() =>
      ReactiveFormFieldState<double>();
}

This is a simplified version of what I use.
Hope That help form me works like a charm,
And it allowed me in that specific case to work with Flutter Masked Text, remember you can create any reactive widget.

**Comment by joanpablo** [comment]
Thanks @marcos930807,

That's a great solution the one you have it.

**Comment by marcos930807** [comment]
Thanks to you for making this incredible library.

**Comment by danbn-100295** [comment]
Wow,thanks @marcos930807 it is good solution!
@joanpablo  thanks you for that package,it so greate for me!

**Comment by joanpablo** [comment]
Hi @danbn-100295,

Thanks once again for the comments and the issue. I guess you have found the solution, so I will close this issue. 

Feel free to open new issues if you have any problem or question about reactive forms.

Good Coding.
