### ISSUE TITLE
PageView wizard style

### ISSUE THREAD

**Issue by combi-35** [joanpablo/reactive_forms#46]
I would like to create an add Event wizard with PageView and nested FormGroup.
PageView is within Scaffold Body.
Next Button is within Scaffold bottomSheet, so there is only one button for the whole screen, which should be en/dis-abled according to the form validity in every PageView screen.
I wonder is there a way to call an update to refresh the UI once the PageView changed and should disable the button?

Current wrong behavior:
1. Start Button disabled
2. Insert text in title
3. Button is enabled because form is valid
4. Change to next PageView Screen
5. pageIsValid method prints out that next form ('date') is invalid (which should be the case), but button stays enabled.

Expected behavior:
1. Start Button disabled
2. Insert text in title
3. Button is enabled because form is valid
4. Change to next PageView Screen
5. Button disabled until date form is valid

**Provider ViewModel**
```
class AddActivityViewModel extends ChangeNotifier {
  
  FormGroup get form => _form;
  get formGeneral => form.control('general');
  get formDate => form.control('date');

  final _form = FormGroup({
    'general': FormGroup({
      'title': FormControl<String>(validators: [Validators.required]),
    }),
    'date': FormGroup({
      'startDate': FormControl<String>(validators: [Validators.required]),
    }),
  });

  // Get formName for PageView index
  String formNameperPage(int pageindex) {
    return _form.controls.keys
        .toList()[pageindex]
        .toString();
  }
  
  // Get valid status for PageView index
  bool pageIsValid(int pageindex) {
    var fname = formNameperPage(pageindex);
    var isValid = _form.control(fname).valid;

    print(fname + " Form isValid " + isValid.toString()); // Actually shows right valid status, but no effect in UI 
    return isValid;
  }
}
```

**Scaffold**

```
class AddActivity extends StatefulWidget {
  @override
  _AddActivityState createState() => _AddActivityState();
}

class _AddActivityState extends State<AddActivity> {
  PageController pageviewController = PageController(initialPage: 0);

  @override
  Widget build(BuildContext context) {
    
    final AddActivityViewModel addActivityVM = Provider.of<AddActivityViewModel>(context);

    return ReactiveForm(
      formGroup: addActivityVM.form,
      child: Scaffold(
        body: SafeArea(
          child: PageView(
            controller: pageviewController,
            children: [
              ReactiveForm(
                formGroup: addActivityVM.formDate,
                child: Column(
                  children: [
                    ReactiveFormField(
                      formControlName: 'startDate',
                    ),
                  ],
                ),
              ),
              ReactiveForm(
                formGroup: addActivityVM.formGeneral,
                child: ReactiveFormField(
                    formControlName: 'title',
                  ),
              ),
            ],
          ),
        ),
        resizeToAvoidBottomInset: true,
        bottomSheet: SafeArea(
          child: Container(
            decoration: BoxDecoration(
              border: Border(
                top: Divider.createBorderSide(context, width: 1.0),
              ),
            ),
            child: ButtonBar(
              buttonMinWidth: 600,
              children: [
                ReactiveFormConsumer(builder: (context, form, child) {
                  return SafeArea(
                    child: MyButton(
                      title: "Next",
                      onPressed: () => nextPage(),
                      isDisabled: !addActivityVM.pageIsValid(pageviewController.page?.toInt()),
                    ),
                  );
                })
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
Hoping to find some help here, thanks in advanced!

**Comment by joanpablo** [comment]
Hi @combi-35,

Thanks for the issue and thanks for using Reactive Forms.

Regarding to your question, **ReactiveFormConsumer** rebuild the button each time the **state** of the Form changes, but in your case the state of the form is not changing from page 1 to page 2, the state remains the same because the parent Form is always invalid (it will be valid when all **enabled** children are valid). 

For some reason your UI is re-build when you insert text (maybe the keyboard pop repaint your screen) and then the button in your first page enabled. But after the second page the button does not rebuild, so the state of the button stay the same.

 In that example you are not making use of **ReactiveFormConsumer**.

I can suggest to you two diferent  ways to handle your needs.
1-) In a traditional way you can create a **ValueNotifier** variable that hold the state of the *ViewModel* and changes its value each time you change the page. Then Wrap the *MyButton* with a **ValueListenableBuilder**. That will rebuild your button.

2-) The Reactive Forms solution: by default disable each *sub-form* and only enable the first one (in the first page), then each time you change the page also enable the child Form of that page. That will change the **state** of the form and the **ReactiveFormConsumer** will do his job and your button will repaint. This way you can just ask for  **addActivityVM.form.valid** to enable/disable the button, you will not need the **pageIsValid** method.

This is because only **enabled** children afects the state of the **Form**. So no mather how many Pages (sub-groups) you have, the parent FormGroup will change valid/invalid depending only of sub-groups that are enabled and valid/invalid. Each time you enable or disable the children, the status of the parent is recalculated.

**Comment by combi-35** [comment]
Thanks for the fast reply!
I am not sure on how to disable a FormGroup, I could only find documentation for disabling a single FormField.
Do I need to iterate over my main form and call markAsDisabled for each subform?
Looks like disabled property is not part of FormGroup?!

**Comment by combi-35** [comment]
Awesome! Thanks for implementing :)
My Submit Button is now in correct state.
