### ISSUE TITLE
Can we get a ReactiveDateTimePicker?

### ISSUE THREAD

**Issue by Reprevise** [joanpablo/reactive_forms#61]
My only issue with this package is that there's no picker to pick the date and time at the same time (_no pun intended_). Can we get a new widget that merges the two pickers? Having two separate fields for the date and time doesn't make a lot of sense. Implementing this would clean up a lot of forms. If not, at least give us a practical example of how to use both pickers in _one_ field to output the date and time.

**Comment by joanpablo** [comment]
Hi @Reprevise,

Thanks for using **Reactive Forms** and for the issue. You are right about the necessity of having a unique widget that can handle both data: date and time, but actually Flutter doesn't has that implementation as a native widget, that's the main reason I haven't included it in Reactive Forms.

But you can easily create your custom Reactive Widget that uses a community plugin that can handle both data, or implement you own custom reactive widget.

Some plugins from community:
. [date_time_picker](https://pub.dev/packages/date_time_picker)

Create a custom Reactive Widget is quite easy and clean. You can check the [Wiki](https://github.com/joanpablo/reactive_forms/wiki/Custom-Reactive-Widgets) tutorial and this [post](https://dev.to/joanpablo/star-rating-with-flutter-reactive-forms-2d52) about how to achieve this.  

I'm planning to create a new package called *Reactive Form Widgets* that include several Reactive Widgets, and maybe that could be one of them. But that will wait a little since there are still some other features I must include in Reactive Forms.

**Comment by nandhakumargdr** [comment]
That's great I'm waiting for Reactive Form Widgets

**Comment by joanpablo** [comment]
Close issue since not recent activity
