### ISSUE TITLE
ReactiveDropDown Field - disabled value

### ISSUE THREAD

**Issue by radvansky-tomas** [joanpablo/reactive_forms#62]
Once ReactiveDropDown field is set to disabled
` form.control('field_name').markAsDisabled();`

Its current value is not being displayed, ie `selectedItemBuilder` is not used.

As workaround you have to utilise `disabledHint` widget and access current form value directly and return your view:
```
.where((element) =>
                    element.type == state.form.control('field_name').value)
```

**Comment by joanpablo** [comment]
Hi @ radvansky-tomas,

Thanks for using reactive forms and thanks for the problem.

Could you give a more complete example to reproduce the error?

The actual version of ** Reactive Forms ** is 7.3.0. Since version 7.0.12 I have already included some code that handles the case of a disabled FormControl linked to a reactive dropdown and the value of the dropdown is always visible (I used the workaround you have proposed in your comment), but maybe it was missing something, please provide a full use case to reproduce the error:

![Annotation 2020-11-23 171441](https://user-images.githubusercontent.com/37339180/100030565-cdd29480-2dc1-11eb-815e-d213ea4c49f8.jpg)

![Annotation 2020-11-23 192309](https://user-images.githubusercontent.com/37339180/100030568-d0cd8500-2dc1-11eb-99d7-7631cab626e6.jpg)

**Comment by radvansky-tomas** [comment]
Thank you for quick reply. So yes you are right, I just updated lib and with latest version **7.3.0** it renders content. However it render widget from `items` and not from `selectedItemBuilder`. Which is in my case wrong...

Let me explain:
First of all my items contains bigger item, effectively `ListTile` widget, whilst selected item is simple `Text`. 

With this version it renders whole ListTile (in ListTile in fact), which cause render issues and content overlaps actual ReactiveDropDownField

**Comment by joanpablo** [comment]
Hi @radvansky-tomas,

You're right about that. I will update the code to take into account the **selectedItemBuidler**. I will notify when it is done.

Could you please show me with some sample code how do you use the  **selectedItemBuidler** to build your Text?? That will help me to find the better implementation. 

Thanks once again.

**Comment by radvansky-tomas** [comment]
Sure my `selectedItemBuidler` is pretty simple:

```
    selectedItemBuilder: (context) {
              return Categories.categories.map<Widget>((Category e) {
                return Container(
                    child: Text(
                  e.label,
                ));
              }).toList();
            },
```

It only builds list `Text` items wrapped in `Container`

**Comment by joanpablo** [comment]
OK, thanks @radvansky-tomas.

I will notify you as soon as possible about the solution so you can test it and close the issue.

**Comment by joanpablo** [comment]
Hi @radvansky-tomas,

I've release v7.4.0 please download it and test again your code.

Thanks.

**Comment by radvansky-tomas** [comment]
Yes that works perfectly @joanpablo, THX for your effort and great lib
