### ISSUE TITLE
How to format a date in datepicker textfield?

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#69]
There is `DateTimeValueAccessor` that is used for parsing date.
But I did not found a way to override it.

**Comment by vasilich6107** [comment]
I've found the solution
I'll add a PR to show how

**Comment by joanpablo** [comment]
Hi @vasilich6107 
Do you think is a good idea to add a dependency to another library in Reactive Forms? I haven't implemented this Date Value Accessor using DateFormat for that reason, because I'm concerned that users of Reactive Forms become to having some compatibility issues of the intl with other libraries. What do you think about it?

If the final though is to use intl, then I think we should remove the default DateTimeValueAccessor and rename your FormattedDateTimeValueAccessor to DateTimeValueAccessor.

Please tell me your opinion.

**Comment by vasilich6107** [comment]
The library `intl` is officially supported by dart team https://github.com/dart-lang/intl
So the compatibility issues are not expected.

If you prefer `purity` we can move the accessor out from lib and leave it only inside `example` folder

**Comment by joanpablo** [comment]
Hi @vasilich6107 

Yes I know the **intl** is official, but my concern is for example that **Reactive Forms** get in conflict with another plugin that uses an older version of **intl**. I know it's a rare situation, I experiment it only once in all my projects. Have you ever had this problem?

**Comment by vasilich6107** [comment]
Yes. My current project has some dependency overrides :-)

```
dependency_overrides:
  gql_link: ^0.3.1-alpha
  gql: ^0.12.4-alpha
  flutter_svg: ^0.19.0
  analyzer: 0.39.15
```
