### ISSUE TITLE
reactive_forms_widgets package

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#71]
I created a package where we can collect some other reactive fields to keep the form clean.
Can we add a reference to the package in readme?
https://pub.dev/packages/reactive_forms_fields

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Sorry for the late answer, I'm moving from country so I'm in the middle of country relocation, that's why I take t long to review your pull requests and issues. And you are right know to fast hahah. 

I will give you my considerations.   You have done an excellent work helping me and contributing with the package and I'm very grateful with you.

Having another packages with useful and advanced *widgets* is something I have wanted since the very first beginning of Reactive Forms, so great job. I don't know right now if it is possible to change the name of the package because I personally prefer: **Reactive Forms Widgets** instead of Reactive Form Fields just to remark that is a package with advanced widgets based on Reactive Forms.

You have made some changes in Reactive Forms that require to upgrade version of Flutter to 1.20. And that is OK, I will upgrade the version and release v8.0.0. That will brake compatibility with Flutter 1.17, but that's OK I think is time to upgrade. So I will fix the CI to pass all test. There are also other issues that require to upgrade Flutter like **autoFillHints**, with this upgrade now we can implement this feature.

About the **intl** package, I prefer for now not including it. In the (wiki)[https://github.com/joanpablo/reactive_forms/wiki/Control-Value-Accessors] of the project there is documentation about how to create Custom Value Accessors and how to implement a Formatted DateTime Value Accessor, and you can add the implementation in the example project. I'm sure that in the future we will include it but I want to add some extra features first before add **intl**.

**Comment by vasilich6107** [comment]
Ok. I'll change the lib name)
It is not very complicated at the beginning.

I'll make another PR with updated DateTime value accessor.

**Comment by vasilich6107** [comment]
https://pub.dev/packages/reactive_forms_widgets

**Comment by joanpablo** [comment]
Hi @vasilich6107,

How do you propose to show the new plugging in the docs of **Reactive Forms**? Feel free for make a pull request in doc and we can work together finding the best way.

Thanks.

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Do you have any ideas about v8 release?

I have prepared some date related fields so I would like to use `DateTimeValueAccessor`

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Let me prepare the documentation related to release.

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I've just released v8.0.0. Please let me know if everything is OK.

**Comment by vasilich6107** [comment]
Hi @joanpablo 
Everything works good.
I released a simplified date picker to the widgets lib. With support of date, time and dateTime modes.

```
 ReactiveDatePickerField(
                formControlName: 'date',
                decoration: const InputDecoration(
                  labelText: 'Date',
                  suffixIcon: Icon(Icons.calendar_today),
                ),
              ),
```

**Comment by vasilich6107** [comment]
I'll update the readme and `examples` a little bit later

**Comment by joanpablo** [comment]
Excellent news @vasilich6107. Great work!!!!

**Comment by joanpablo** [comment]
Hey @vasilich6107 What if instead of named it **ReactiveDatePickerField** you set *ReactiveDateTimePicker* as the name?

**Comment by vasilich6107** [comment]
Sounds reasonable. I'll make a fix

**Comment by joanpablo** [comment]
Hi @vasilich6107, 

I think I will remove later the code that shows how to install the **reactive_forms_widgets** from README.md, and will left just the explanation about this new library.


I will remove this:
>```dart
>dependencies:
>  flutter:
>    sdk: flutter
>
> reactive_forms_widgets: latest
>```
> Then run the command flutter packages get on the console.

And add something like: "Please visit the package repository to know how to install it and read the doc about the widgets it contains.... etc" something like that.

**Comment by vasilich6107** [comment]
ok

**Comment by vasilich6107** [comment]
Closing this issue as there is nothing more to discuss :-)
