### ISSUE TITLE
Inline validators and validation messages

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#81]
Currently we need to manage validation in 2 places.

First place is the validators definition - we need to specify validation rule.
Second place is the `validationMessages` - we need to specify a map to define the wording for specific message.

This seems to be annoying  - I need to do the same thing in two places.
- when I define validators
- when I need to change validation rule and message
- when I need to delete validation rule and message

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Could you please give an example of the issue to fully understand it?

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I made a separation between the business logic of the validator and the messages to show when the validator marks the control as invalid.

In my opinion is not good to define error *text messages* in controller classes, because text messages can be translated into several languages, and is the UI (context), responsible for showing the right message according to the error (represented by a **key**, for example: ValidationMessages.required). So in the definition of a form control, you define the logic of the validation and the key of the error, then in the UI, you define the text related to that key, in the language of the final user.

That is why is a separation logic when defining the validator (controller class) and specifying the message text (UI classes).

**Comment by joanpablo** [comment]
I am going to close this issue for now by not receiving feedback for several days.
Please feel free to open it again or a new one.
