### ISSUE TITLE
Error message pushes widget up

### ISSUE THREAD

**Issue by Fiyiin** [joanpablo/reactive_forms#90]
When there's an error, the error message pushes up the Reactive widget. Is there a way to change this behavior?
(The phone number widget in the screenshot)

![photo_2021-02-10_13-03-29](https://user-images.githubusercontent.com/38258693/107507832-6c3fec00-6ba0-11eb-80c5-03dd716ed7cb.jpg)

**Comment by joanpablo** [comment]
Hi @Fiyiin,

Thanks for using **Reactive Forms**. This is a behavior in Flutter for errors when showing up, they push other widgets down, or in your case, because of some custom layout, it is pushing your widget up.

You can modify your layout to push the other controls down, or contemplate the space of the message when designing the layout.

**Comment by Fiyiin** [comment]
@joanpablo Thank you for the support. You're doing a great job

**Comment by joanpablo** [comment]
Thanks for your kind words @Fiyiin.
