### ISSUE TITLE
Question: How to get form.valid outside ReactiveForm widget?

### ISSUE THREAD

**Issue by hayashi-ay** [joanpablo/reactive_forms#96]
Hi there,

Thanks in advance.

My question is is there any way to get form.valid outside `ReactiveForm`.
I know `ReactiveFormConsumer` watches the status of the form and rebuild UI when it is changed but I want to place button widgets outside `ReactiveForm`.

The example code is: 

```dart
// @dart=2.9
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:reactive_forms/reactive_forms.dart';

final profileFormGroup = Provider<FormGroup>((ref) {
  return FormGroup(
    {
      'lastName': FormControl<String>(
        validators: [Validators.required],
      ),
    },
  );
});

class ProfileScreen extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final formGroup = useProvider(profileFormGroup);

    void registerUserInfo() {
      print(formGroup.valid);
    }

    return Scaffold(
      appBar: AppBar(title: const Text('Register Profile')),
      body: SafeArea(
        child: Container(
          padding: const EdgeInsets.all(24),
          child: ReactiveForm(
            formGroup: formGroup,
            child: ReactiveTextField(
              formControlName: 'lastName',
            ),
          ),
        ),
      ),
      bottomNavigationBar: ElevatedButton(
        child: const Text('button'),
        // formGroup.valid is not changed.
        onPressed: formGroup.valid ? registerUserInfo : null,
      ),
    );
  }
}

```

**Comment by vasilich6107** [comment]
Hi @hayashi-ay 
You can move `ReactiveForm` upper in the tree above the `Scaffold` widget.
This should help you

**Comment by hayashi-ay** [comment]
@vasilich6107 Thanks a lot. It worked fine by wrapping `ElevatedButton` by `ReactiveFormConsumer` besides your suggestion.
```dart
bottomNavigationBar: ReactiveFormConsumer(
          builder: (context, form, child) {
            return ElevatedButton(
              child: const Text('button'),
              onPressed: formGroup.valid ? registerUserInfo : null,
            );
          },
        ),
```

**Comment by joanpablo** [comment]
Hi @hayashi-ay,

Thanks for using Reactive Forms and for the issue.

If you want to listen for changes in the *status* of the FormGroup (to be notified if the form is valid, pending, or invalid) you will need to subscribe to **FormGroup.statusChanged**. Widgets like **ReactiveFormConsumer** and **ReactiveStatusListenableBuilder** are just wrappers around **InheritedStreamer**(a Reactive Form library implementation of InheritedNotifier but using Streams instead of Listenables) and **StreamBuilder**. 

That means that you can use these widgets to simplify the boilerplate code of using StreamBuilders for listening to changes or you can directly use StreamBuilders or just create your widget for listening to changes.

Also, remember that you can always use **formGroup.statusChanged.listen** to add a listener/callback function when the status in Form changes. What approach to use is up to you depending on your goals.

Looking only at your sample code, I will recommend using **ReactiveFormConsumer** of **ReactiveStatusListenableBuilder**.

In the [Enable/Disable Submit Button](https://github.com/joanpablo/reactive_forms#enabledisable-submit-button) section of the documentation, you will find some examples on how to update your button depending on the state of the form.

I hope All these tips helps you to better understand the logic of status notifications of Reactive Forms controls and let you find the best solution. Please don't hesitate to ask again for some help. And please let's know if you have solved the issue.  

Thanks

**Comment by hayashi-ay** [comment]
Hi @joanpablo ,

Thanks for the detail explanation. 
I finally use `formGroup.statusChanged.listen` with using `StateProvider`.

```dart
final isFormValidProvider = StateProvider<bool>((ref) {
  return false;
});

class ProfileScreen extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final formGroup = useProvider(profileFormGroup);
    final isFormValid = useProvider(isFormValidProvider);
    formGroup.statusChanged.listen((event) {
      isFormValid.state = formGroup.valid;
    });

   ...
}
```

**Comment by joanpablo** [comment]
Hi @hayashi-ay,

I would like to suggest, that be aware of using *formGroup.statusChanged.listen* inside the **Widget build(BuildContext context)** method. That means that each time the widget rebuilds, it will add a callback, and maybe you should add it only once.   Almost always this is used inside a Stateful Widget or a *controller/bloc/viewmodel* in a state management library like Provider or Bloc, and this is because you will need to subscribe to state change only once.

Have a nice day.

**Comment by hayashi-ay** [comment]
@joanpablo Thanks a lot. I changed my code without using *statusChanged.listen*.

```dart
// @dart=2.9
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:reactive_forms/reactive_forms.dart';

final profileFormGroup = Provider<FormGroup>((ref) {
  return FormGroup(
    {
      'lastName': FormControl<String>(
        validators: [Validators.required],
      ),
    },
  );
});

final formStatusChangedProvider = StreamProvider<ControlStatus>((ref) {
  return ref.watch(profileFormGroup).statusChanged;
});

final isFormValidProvider = Provider<bool>((ref) {
  final status = ref.watch(formStatusChangedProvider);
  if (status.data?.value != null) {
    return status.data.value == ControlStatus.valid;
  }
  return false;
});

class ProfileScreen extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final formGroup = useProvider(profileFormGroup);
    final isFormValid = useProvider(isFormValidProvider);

   ...
}
```

**Comment by joanpablo** [comment]
Hi @hayashi-ay,

It is good to know that you have solved the issue. Don't hesitate to open another or reopen this one if you have any other questions.

Best regards
